DROP TABLE IF EXISTS shapes CASCADE;
DROP TABLE IF EXISTS colors CASCADE;
DROP TABLE IF EXISTS valences CASCADE;
DROP TABLE IF EXISTS trials CASCADE;

CREATE TABLE shapes (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE colors (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE valences (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE trials (
  id SERIAL PRIMARY KEY NOT NULL,
  left_shape_id INTEGER REFERENCES shapes(id) ON DELETE CASCADE,
  left_color_id INTEGER REFERENCES colors(id) ON DELETE CASCADE,
  left_valence_id INTEGER REFERENCES valences(id) ON DELETE CASCADE,
  right_shape_id INTEGER REFERENCES shapes(id) ON DELETE CASCADE,
  right_color_id INTEGER REFERENCES colors(id) ON DELETE CASCADE,
  right_valence_id INTEGER REFERENCES valences(id) ON DELETE CASCADE
);