DROP TABLE IF EXISTS shapes CASCADE;
DROP TABLE IF EXISTS colors CASCADE;
DROP TABLE IF EXISTS valences CASCADE;
DROP TABLE IF EXISTS trials CASCADE;

CREATE TABLE shapes (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE colors (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE valences (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE trials (
  id SERIAL PRIMARY KEY NOT NULL,
  shape_id INTEGER REFERENCES shapes(id) ON DELETE CASCADE,
  color_id INTEGER REFERENCES colors(id) ON DELETE CASCADE,
  valence_id INTEGER REFERENCES valences(id) ON DELETE CASCADE,
  rewards INTEGER
);