DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS baits CASCADE;
DROP TABLE IF EXISTS trials CASCADE;
DROP TABLE IF EXISTS user_trial CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  is_female BOOLEAN NOT NULL,
  age SMALLINT NOT NULL
);

CREATE TABLE categories (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  positive DECIMAL NOT NULL,
  reward DECIMAL NOT NULL
);

CREATE TABLE baits (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE trials (
  id SERIAL PRIMARY KEY NOT NULL,
  session SMALLINT,
  bait_1_category INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  bait_2_category INTEGER REFERENCES categories(id) ON DELETE CASCADE,
  bait_3_category INTEGER REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE user_trial (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  trial_id INTEGER REFERENCES trials(id) ON DELETE CASCADE,
  bait_1 INTEGER REFERENCES baits(id) ON DELETE CASCADE,
  bait_2 INTEGER REFERENCES baits(id) ON DELETE CASCADE,
  bait_3 INTEGER REFERENCES baits(id) ON DELETE CASCADE,
  bait_choice INTEGER NOT NULL,
  is_positive BOOLEAN NOT NULL,
  has_reward BOOLEAN NOT NULL
);